version: "3"
services:
   couchbase:
     build: couchbase/
     container_name: urlshortener-couchbase
     ports:
       - "8091-8094:8091-8094"
       - "11210:11210"
     volumes:
       - couchbase-urlshortener:/opt/couchbase/var
    
   golang:
     build: ../
     container_name: urlshortener-app
     ports:
       - "1323:1323"
       
volumes:
   couchbase-urlshortener: